services:
  - type: web
    name: invoice-flask
    env: python
    plan: free
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: DB_HOST
        value: sql12.freesqldatabase.com
      - key: DB_USER
        value: sql12793850
      - key: DB_PASSWORD
        value: XtmBdMHs8T
      - key: DB_NAME
        value: sql12793850
